version: '3'
services:
  app:
    build: .
    container_name: homepage
    ports:
      - 5000:5000
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./prompts.db:/app/prompts.db

    restart: unless-stopped