version: '3'
services:
  app:
    build: .
    container_name: prompt_manager
    ports:
      - 5000:5000
    volumes:
      - /home/pi/docker/prompt_manger/static/uploads:/app/static/uploads
      - /home/pi/docker/prompt_manger/database:/app/instance

    restart: unless-stopped