version: '3'
services:
  app:
    build: .
    container_name: prompt_manager
    ports:
      - ${HOST_PORT}:5000
    volumes:
      - ${DIR_BASE}/prompt_manger/static/uploads:/app/static/uploads
      - ${DIR_BASE}/prompt_manger/database:/app/database

    restart: unless-stopped
