"""seed en texte

Revision ID: 150fb81d8584
Revises: da1bb6a47ebb
Create Date: 2026-09-30 15:42:19.525058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150fb81d8584'
down_revision = 'da1bb6a47ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.alter_column('seed',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.alter_column('seed',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
