"""version3

Revision ID: 5347f99b3176
Revises: 6bc15a214f80
Create Date: 2025-09-12 08:38:33.417537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5347f99b3176'
down_revision = '6bc15a214f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('prompt', sa.TEXT(), nullable=False),
    sa.Column('tags', sa.VARCHAR(length=120), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=120), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('seed', sa.INTEGER(), nullable=True),
    sa.Column('steps', sa.INTEGER(), nullable=True),
    sa.Column('checkpoint', sa.TEXT(), nullable=True),
    sa.Column('loras', sa.TEXT(), nullable=True),
    sa.Column('neg_prompt', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
