"""Ajout de 5 champs

Revision ID: 6bc15a214f80
Revises: 
Create Date: 2025-08-28 16:10:16.339623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc15a214f80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('steps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('checkpoint', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('loras', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('neg_prompt', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_column('neg_prompt')
        batch_op.drop_column('loras')
        batch_op.drop_column('checkpoint')
        batch_op.drop_column('steps')
        batch_op.drop_column('seed')

    # ### end Alembic commands ###
