"""Initial

Revision ID: a76175ba62e3
Revises: 
Create Date: 2026-03-31 12:59:26.684666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76175ba62e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='fk_category_parent'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=120), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('checkpoint', sa.Text(), nullable=True),
    sa.Column('cfg', sa.Float(), nullable=True),
    sa.Column('loras', sa.Text(), nullable=True),
    sa.Column('neg_prompt', sa.Text(), nullable=True),
    sa.Column('prompt_raw', sa.JSON(), nullable=True),
    sa.Column('sampler', sa.String(length=120), nullable=True),
    sa.Column('scheduler', sa.String(length=120), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('image_filename', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_prompt_category'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompts')
    op.drop_table('categories')
    # ### end Alembic commands ###
