"""Ajout hash

Revision ID: da1bb6a47ebb
Revises: 59e78dc1d6f1
Create Date: 2026-09-23 14:57:26.741947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1bb6a47ebb'
down_revision = '59e78dc1d6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_prompts_image_hash'), ['image_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_image_hash'))
        batch_op.drop_column('image_hash')

    # ### end Alembic commands ###
