name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flask flask_sqlalchemy flask_wtf wtforms
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --exit-zero > pylint.log

    - name: Create pylint score badge
      run: |
        mkdir -p badges
        SCORE=$(grep "Your code has been rated at" pylint.log | tail -1 | awk '{print $7}' | cut -d/ -f1)
        echo "score=${SCORE}" >> $GITHUB_ENV

    - name: Upload badge
      uses: emibcn/badge-action@v2
      with:
        label: "pylint ${{ matrix.python-version }}"
        status: "${{ env.score }}/10"
        color: "brightgreen"
        path: "badges/pylint-${{ matrix.python-version }}.svg"
